// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RavelMachineStatus.
const (
	Error    RavelMachineStatus = "error"
	Running  RavelMachineStatus = "running"
	Starting RavelMachineStatus = "starting"
	Stopped  RavelMachineStatus = "stopped"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// RavelMachine defines model for RavelMachine.
type RavelMachine struct {
	// Id Machine unique identifier
	Id string `json:"id"`

	// InitDriveId Initial drive identifier for the machine
	InitDriveId string `json:"init_drive_id"`

	// RootDriveId Root drive identifier for the machine
	RootDriveId string           `json:"root_drive_id"`
	Spec        RavelMachineSpec `json:"spec"`

	// Status Status of the machine
	Status RavelMachineStatus `json:"status"`
}

// RavelMachineSpec defines model for RavelMachineSpec.
type RavelMachineSpec struct {
	// Image Image used by the machine
	Image string `json:"image"`

	// Memory Memory size in MB
	Memory int64 `json:"memory"`

	// Vcpus Number of virtual CPUs
	Vcpus int64 `json:"vcpus"`
}

// RavelMachineStatus Status of the machine
type RavelMachineStatus string

// CreateMachineJSONRequestBody defines body for CreateMachine for application/json ContentType.
type CreateMachineJSONRequestBody = RavelMachineSpec

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ExitWorker request
	ExitWorker(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListMachines request
	ListMachines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMachineWithBody request with any body
	CreateMachineWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateMachine(ctx context.Context, body CreateMachineJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteMachine request
	DeleteMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMachine request
	GetMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMachineLogs request
	GetMachineLogs(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartMachine request
	StartMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopMachine request
	StopMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ExitWorker(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExitWorkerRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListMachines(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListMachinesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMachineWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMachineRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMachine(ctx context.Context, body CreateMachineJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMachineRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteMachineRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMachineRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMachineLogs(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMachineLogsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartMachineRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopMachine(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopMachineRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExitWorkerRequest generates requests for ExitWorker
func NewExitWorkerRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/exit")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListMachinesRequest generates requests for ListMachines
func NewListMachinesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateMachineRequest calls the generic CreateMachine builder with application/json body
func NewCreateMachineRequest(server string, body CreateMachineJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateMachineRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateMachineRequestWithBody generates requests for CreateMachine with any type of body
func NewCreateMachineRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteMachineRequest generates requests for DeleteMachine
func NewDeleteMachineRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMachineRequest generates requests for GetMachine
func NewGetMachineRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMachineLogsRequest generates requests for GetMachineLogs
func NewGetMachineLogsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartMachineRequest generates requests for StartMachine
func NewStartMachineRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopMachineRequest generates requests for StopMachine
func NewStopMachineRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/machines/%s/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ExitWorkerWithResponse request
	ExitWorkerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ExitWorkerResponse, error)

	// ListMachinesWithResponse request
	ListMachinesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListMachinesResponse, error)

	// CreateMachineWithBodyWithResponse request with any body
	CreateMachineWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMachineResponse, error)

	CreateMachineWithResponse(ctx context.Context, body CreateMachineJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMachineResponse, error)

	// DeleteMachineWithResponse request
	DeleteMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteMachineResponse, error)

	// GetMachineWithResponse request
	GetMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMachineResponse, error)

	// GetMachineLogsWithResponse request
	GetMachineLogsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMachineLogsResponse, error)

	// StartMachineWithResponse request
	StartMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartMachineResponse, error)

	// StopMachineWithResponse request
	StopMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopMachineResponse, error)
}

type ExitWorkerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r ExitWorkerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExitWorkerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListMachinesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Machines *[]RavelMachine `json:"machines,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListMachinesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListMachinesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateMachineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		MachineId *string `json:"machineId,omitempty"`
	}
	JSON400 *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateMachineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateMachineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteMachineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteMachineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteMachineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMachineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RavelMachine
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMachineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMachineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetMachineLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetMachineLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMachineLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartMachineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StartMachineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartMachineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopMachineResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *ErrorResponse
	JSON404      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StopMachineResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopMachineResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ExitWorkerWithResponse request returning *ExitWorkerResponse
func (c *ClientWithResponses) ExitWorkerWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ExitWorkerResponse, error) {
	rsp, err := c.ExitWorker(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExitWorkerResponse(rsp)
}

// ListMachinesWithResponse request returning *ListMachinesResponse
func (c *ClientWithResponses) ListMachinesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListMachinesResponse, error) {
	rsp, err := c.ListMachines(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListMachinesResponse(rsp)
}

// CreateMachineWithBodyWithResponse request with arbitrary body returning *CreateMachineResponse
func (c *ClientWithResponses) CreateMachineWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateMachineResponse, error) {
	rsp, err := c.CreateMachineWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMachineResponse(rsp)
}

func (c *ClientWithResponses) CreateMachineWithResponse(ctx context.Context, body CreateMachineJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateMachineResponse, error) {
	rsp, err := c.CreateMachine(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMachineResponse(rsp)
}

// DeleteMachineWithResponse request returning *DeleteMachineResponse
func (c *ClientWithResponses) DeleteMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteMachineResponse, error) {
	rsp, err := c.DeleteMachine(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteMachineResponse(rsp)
}

// GetMachineWithResponse request returning *GetMachineResponse
func (c *ClientWithResponses) GetMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMachineResponse, error) {
	rsp, err := c.GetMachine(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMachineResponse(rsp)
}

// GetMachineLogsWithResponse request returning *GetMachineLogsResponse
func (c *ClientWithResponses) GetMachineLogsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetMachineLogsResponse, error) {
	rsp, err := c.GetMachineLogs(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMachineLogsResponse(rsp)
}

// StartMachineWithResponse request returning *StartMachineResponse
func (c *ClientWithResponses) StartMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartMachineResponse, error) {
	rsp, err := c.StartMachine(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartMachineResponse(rsp)
}

// StopMachineWithResponse request returning *StopMachineResponse
func (c *ClientWithResponses) StopMachineWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopMachineResponse, error) {
	rsp, err := c.StopMachine(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopMachineResponse(rsp)
}

// ParseExitWorkerResponse parses an HTTP response from a ExitWorkerWithResponse call
func ParseExitWorkerResponse(rsp *http.Response) (*ExitWorkerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExitWorkerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListMachinesResponse parses an HTTP response from a ListMachinesWithResponse call
func ParseListMachinesResponse(rsp *http.Response) (*ListMachinesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListMachinesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Machines *[]RavelMachine `json:"machines,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateMachineResponse parses an HTTP response from a CreateMachineWithResponse call
func ParseCreateMachineResponse(rsp *http.Response) (*CreateMachineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateMachineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			MachineId *string `json:"machineId,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseDeleteMachineResponse parses an HTTP response from a DeleteMachineWithResponse call
func ParseDeleteMachineResponse(rsp *http.Response) (*DeleteMachineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteMachineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetMachineResponse parses an HTTP response from a GetMachineWithResponse call
func ParseGetMachineResponse(rsp *http.Response) (*GetMachineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMachineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RavelMachine
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetMachineLogsResponse parses an HTTP response from a GetMachineLogsWithResponse call
func ParseGetMachineLogsResponse(rsp *http.Response) (*GetMachineLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMachineLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseStartMachineResponse parses an HTTP response from a StartMachineWithResponse call
func ParseStartMachineResponse(rsp *http.Response) (*StartMachineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartMachineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseStopMachineResponse parses an HTTP response from a StopMachineWithResponse call
func ParseStopMachineResponse(rsp *http.Response) (*StopMachineResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopMachineResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Exit worker
	// (POST /api/v1/exit)
	ExitWorker(ctx echo.Context) error
	// List all machines
	// (GET /api/v1/machines)
	ListMachines(ctx echo.Context) error
	// Create a machine
	// (POST /api/v1/machines)
	CreateMachine(ctx echo.Context) error
	// Delete a machine by its ID
	// (DELETE /api/v1/machines/{id})
	DeleteMachine(ctx echo.Context, id string) error
	// Get a specific machine by its ID
	// (GET /api/v1/machines/{id})
	GetMachine(ctx echo.Context, id string) error
	// Get logs for a machine by its ID
	// (GET /api/v1/machines/{id}/logs)
	GetMachineLogs(ctx echo.Context, id string) error
	// Start a machine by its ID
	// (POST /api/v1/machines/{id}/start)
	StartMachine(ctx echo.Context, id string) error
	// Stop a machine by its ID
	// (POST /api/v1/machines/{id}/stop)
	StopMachine(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ExitWorker converts echo context to params.
func (w *ServerInterfaceWrapper) ExitWorker(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ExitWorker(ctx)
	return err
}

// ListMachines converts echo context to params.
func (w *ServerInterfaceWrapper) ListMachines(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMachines(ctx)
	return err
}

// CreateMachine converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMachine(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMachine(ctx)
	return err
}

// DeleteMachine converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMachine(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMachine(ctx, id)
	return err
}

// GetMachine converts echo context to params.
func (w *ServerInterfaceWrapper) GetMachine(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMachine(ctx, id)
	return err
}

// GetMachineLogs converts echo context to params.
func (w *ServerInterfaceWrapper) GetMachineLogs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMachineLogs(ctx, id)
	return err
}

// StartMachine converts echo context to params.
func (w *ServerInterfaceWrapper) StartMachine(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartMachine(ctx, id)
	return err
}

// StopMachine converts echo context to params.
func (w *ServerInterfaceWrapper) StopMachine(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StopMachine(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/exit", wrapper.ExitWorker)
	router.GET(baseURL+"/api/v1/machines", wrapper.ListMachines)
	router.POST(baseURL+"/api/v1/machines", wrapper.CreateMachine)
	router.DELETE(baseURL+"/api/v1/machines/:id", wrapper.DeleteMachine)
	router.GET(baseURL+"/api/v1/machines/:id", wrapper.GetMachine)
	router.GET(baseURL+"/api/v1/machines/:id/logs", wrapper.GetMachineLogs)
	router.POST(baseURL+"/api/v1/machines/:id/start", wrapper.StartMachine)
	router.POST(baseURL+"/api/v1/machines/:id/stop", wrapper.StopMachine)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXW2/jNhP9KwS/D+iLEjndoA96SzaLhdGkWCQo+rAIFow0sicrkVxy6Nob6L8XQ/oq",
	"y8m6QAv3JTF4mcs5Z2aoF1ma1hoNmrwsXqQvp9Cq+PODc8bdg7dGe+AF64wFRwhxuwXv1SRu0MKCLKQn",
	"h3oiuy5brZinZyhJdpm8VzNo7lQ5RT1gCyv+W4EvHVpCo2Uhl4dF0PgtgMAKNGGN4GTWd5hJ1EhfKocz",
	"+DJka6yRUDUintgyJWrjBE1BtMvIBkw7Y14zfW8M/S273kLJ5v7voJaF/F++ISJfspBvo/bA5/keKQr+",
	"qJvpBvPi4FtAB5UsPjPofeD62a69LcN9fIPZh2VOPXbbpU56pPCyCB4q8bR4C60WWuMWAyqJ68LjdxCo",
	"xd21zGRtXKtIFhI1/XK5sYaaYAKOzc1KmzDctfZbaJ/ACVOLGToKqhHvP/3uf8RkH9uY8srPOvw38Vtz",
	"uxtXWue4dmECHVp250k5YqQy6YLW6ZcnYy0wicCVvOV8q1A9lMEhLR5YN4muq0BT4/C7Ss5fJHIIU1BV",
	"rD2tWrYxP1MWz77CYgOGsvgrLGTXxYKsTWwNSA1sqtmLq09jxgWcT6ldnI8YBWNBK4uykO/OR+cjmUmr",
	"aBrjyZXFfHaRwxwpisv4+J8lFmMcV7KQH+ZIfxj3Ncboll0r3v95NBpANJQl+FQUPrStYnFFI+LPZIV3",
	"Vq6XiEdzExjwfoueVike8F8aTaDjXWVtg2W8nT/7BHIq3IE2u+UaCdqjKl9uWrFyTi2GejMv7WJzJRr0",
	"xGpbO9+FibMVqmm29rMDtLx3oAju1orlIgFP16ZaHAXKcV2yS/W4Q8LFUf5grlrbwBYDMZ3nejp7jrAO",
	"sjSufmgc7kO+GnZlhKsSPsmzDk2zYG+XR2roNbh25/pAMNeqEkueesQnNoVat6ChIslfsOpSxTVAsK+J",
	"m7i+0YRVTrVA4LwsPh96Boxv4rSSRWwMmz6Upta69ZILkG0B0eficU8Xl4efHimBITYu/z02VsFoQ6I2",
	"QVc9ThKaG054mCJ5BqzLhrvVR6BTQX/0j3SBIRxvgBQ2UAkeTTzN0WihnkygnaF6avR+BBJK8OsLayyH",
	"SD5UgnljJocn1kYDt3zs1HRAMKccZqDpzJMD1e5C3je4BysntfcKP0Vum1Wg6ihu44vv8GvogbdPqsaH",
	"fcY0Tq7D/tTjKaJ5NEHGvsaPsf8JeuInxAk9R06sgpnHA8KIH1duNkzqrSlVI9K+zGRwDX9iEdkizxve",
	"mxpPxbvRaCS7x+6vAAAA//+tIuEbpREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
