@baseUrl = http://localhost:3000/api/v1
@apiKey = very secret password

###
# @name CreateMachine
POST {{baseUrl}}/machines HTTP/1.1
Content-Type: application/json
x-api-key: {{apiKey}}

{
	"image": "nginx",
	"memory": 512,
	"vcpus": 1
}

###
# @name GetMachine
# @prompt machineId
GET {{baseUrl}}/machines/{{machineId}}
x-api-key: {{apiKey}}


###
# @name GetMachineLogs
# @prompt machineId
GET {{baseUrl}}/machines/{{machineId}}/logs
x-api-key: {{apiKey}}

###
# @name ListMachines
GET {{baseUrl}}/machines
x-api-key: {{apiKey}}


###
# @name StartMachine
# @prompt machineId
POST  {{baseUrl}}/machines/{{machineId}}/start
x-api-key: {{apiKey}}


###
# @name StopMachine
# @prompt machineId
POST {{baseUrl}}/machines/{{machineId}}/stop
x-api-key: {{apiKey}}


###
# @name DeleteMachine
# @prompt machineId
DELETE {{baseUrl}}/machines/{{machineId}}
x-api-key: {{apiKey}}

###
# @name ExitWorker
POST {{baseUrl}}/exit
x-api-key: {{apiKey}}